tari-project/tari-crypto

Cargo.toml
README.md
src/wasm/commitments.rs
src/wasm/key_utils.rs
src/wasm/keyring.rs
wasm-demo.js

Bump version to 0.2.0
* Breaking change: `KeyRing.sign` doesn't take a nonce any more. It's not needed, and why risk someone re-using it?
* New method: `key_utils.sign` to sign keys not in the key ring
* New module: Commitments

WASM commitments

---

Cargo.toml
src/lib.rs

export the whole `tari_utilities` crate rather than bits of it.
It makes using tari-crypto in other projects that also use tari_crypto
**much** more convenient.

Utils export

---

Cargo.toml

Bump to blake2 v0.8.1

---

Cargo.toml
src/ristretto/ristretto_keys.rs

The current debug format for pubkeys is not very useful right now, and
many default logs in the tari node software make use of debug, resulting
in very low S:N.

Make Public Key Debug format human readable

---

Cargo.toml

That would allow to use traits from _tari_utilities:0.2_ for both _tari_crypto_ and _tari_mmr_
```
❯ cargo tree | less | grep tari   
emoji_id v0.1.0 (/Users/max/src/tari/emoji.id/emoji_id)
├── tari_crypto v0.4.0
│   └── tari_utilities v0.1.2
├── tari_mmr v0.2.0
│   ├── tari_storage v0.1.0
│   │   ├── tari_utilities v0.1.2 (*)
│   └── tari_utilities v0.2.0
```

Update tari_utilities dependency

---

Cargo.toml
src/lib.rs
src/ristretto/ristretto_sig.rs
src/ristretto/utils.rs
src/script/error.rs
src/script/mod.rs
src/script/op_codes.rs
src/script/serde.rs
src/script/stack.rs
src/script/tari_script.rs

Tari script is heavily inspired by Bitcoin script in that:
* It is non-Turing complete
* Is stack based
* Shares many of the same opcodes
For script safety, the Rust type system is leveraged so that
* Opcode operations on inappropriate input data is impossible
* Bounds checking is done on arithmetic operations
Tari script differs from Bitcoin script in that:
* Succesful execution requires exactly zero to be on the stack after
completion
* Blake256 and Curve25519 are the default hash and elliptic curves
respectively.
For a PoC, pay-to-public-key-hash (P2PKH) is implemented in the tests.
Serde support is provided.
```
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Opcode {
/// Push the associated 32-byte value onto the stack
PushHash(Box<HashValue>),
/// Hash to top stack element with the …
```

Tari Script

---

src/ristretto/mod.rs
src/ristretto/script_commitment.rs
src/script/error.rs
src/script/mod.rs
src/script/op_codes.rs
src/script/tari_script.rs

The ScriptCommitment type is a container struct that holds the
(secret and public) information necessary to derive the corresponding
Pedersen commitment.
The script commitment is a modified Pedersen commitment of the form
SC = C + H(C||s) where
SC is the script commitment
C is the "naked" pedersen commitment
H is a hash function (with 32 byte digest)
s is the hash of the serialised Tari script
To achieve this:
First, we add the TariScript::as_hash function, which lets us easily
calculate s.
Then we add the `ScriptCommitmentFactory` type that takes a blinding
factor, value and Tari script and calculates the intermediate terms in
the equation above, returning them in a `ScriptCommitment` struct.
The `ScriptCommitmentFactory` can take this object and generate the
equivalent Pedersen …

Develop the ScriptCommitment wrapper type.

---

Cargo.toml
src/hash/sha3.rs

Add sha3 as a hash function for tari_crypto
Refactor crypto to better accommodate more than one hash function. 
This Pr adds in the sh3 as a hash function. Its added in the same way as as blake2. This will allow tari to swop hash functions between the two with just the changed of a type. 
The tari_crypto crate is also modified to allow more than one hash function to be supported easily. 
Added a pub use to not break the moving of the blake2 hash function.

Add Sha3 hash function

---

src/wasm/key_utils.rs
src/wasm/keyring.rs
wasm-demo.js

In some cases, the public nonce used in the signature is committed and
used in the challenge. These extra methods allow signing with a private
nonce to accommodate that. There is also support for signing a pre-hashed
byte array instead of a string message

Add signing methods for pre-determined nonces

---

Cargo.toml
build.rs

* Match bulletproof and tari_crypto dependency versions
* Bump crtate version to v0.8.1

Align dalek version numbers

---

Cargo.toml
libtari/demo.c
src/ffi/keys.rs

The security audit was failing on tari-project/tari because it had a higher required version of `serde`, which became a transitive dependency of this repo with the introduction of` cbindgen`. 
This PR updates to cbindgen dependency, and fixes some build issues encountered afterwards. 
Tested with:

Bump cbindgen dep to fix security audit on Tari repo

---

src/wasm/key_utils.rs

pubkey_from_hex function deserializes tari public key hex (Ristretto)
and returns a javascript object with the decoded public key.
If the public key does not represent a valid public key, boolean `false`
is returned. This is useful for validating the public key in javascript
environments.

pubkey_from_hex WASM function

---

.github/workflows/grcov.yml
build.rs

* Only run lib tests (doc tests shouldn't count towards coverage)
* Fix stack overflow issue -- don't run FFI binding generation and change panic strategy

Fix grcov action

---

Cargo.toml
Makefile
README.md

This PR resolves two inter-related issues:
* Tari_crypto WASM doesn't work on Safari currently
* wasm_pack won't compile `clear_on_drop` (need to use either `no_cc` or `nightly` flags)
The latter was fixed by including the `no-cc` flag in the `wasm` flag. This causes issues with libraries that use tari_crypto as a dependency for building wasm, but don't want to export the wasm functions defined here. So they either cannot build, or they switch on the `wasm` feature, but then Safari isn't supported.
This PR simply decouples the two issues.
You can export wasm with the `wasm` flag; and control the `clear_on_drop` compilation using either the `no_cc` or `no_cc_nightly` flags.

Expose fine-grained control of cc feature flags

---

src/ristretto/musig.rs
src/script/error.rs
src/script/mod.rs
src/script/op_codes.rs
src/script/stack.rs
src/script/tari_script.rs

Opcodes and script logic updated from [RFC-0202](https://rfc.tari.com/RFC-0202_TariScriptOpcodes.html). Includes tests for new opcodes.

Update TariScript/opcodes and implementation to latest RFC-0202 

---

src/script/stack.rs
src/script/tari_script.rs

Make storing the ExecutionStack in a database easier, this was manually implemented for TariScript but I think the derives are fine for the stack.

Add serde to the ExecutionStack

---

src/ristretto/ristretto_com_sig.rs
src/signatures/commitment_signature.rs

This implements the canonical way to encode CommitmentSignature.
i.e `bytes(R) || bytes(u) || bytes(v)`
Unfortunately, implementing `ByteArray` is not possible (maybe with unsafe) as things stand 
because the trait requires `as_bytes` to be implemented which implies 
something owns the contiguous bytes that the slice is referencing, which is not the case.
The script_signature needs to be committed to in the input hash. ~~One way to do that is to calculate `uG + vH` where `u` and `v` are the public signatures (i.e use  `calc_signature_verifier(&CommitmentFactory::default()).as_bytes()`. However, this requires all clients to be able to create commitments on G and H (extra wasm bindings etc) vs simply concatenating bytes.~~ EDIT: was obviously tired ;) can  just use `bytes(u)`, `bytes(v)` …

Add `to_vec` function to comm sig

---

src/hash/blake2.rs

Remove heap allocation when obtaining a blake2b hash result.

Remove extra heap allocation in Blake256

---

src/signatures/schnorr.rs

Use little-endian byte order (32 bytes comparison, 0 allocations) instead of
hex order (64 byte comparison + 2 allocations). These comparisons are
equivalent (NB because this impl is consensus code).

Minor optimisation to SchnorrSignature ord impl

---

src/script/op_codes.rs
src/script/stack.rs

- [minor perf] Use count instead of collect in `pop_n_plus_one_contains`
- [test] Use `PartialEq` impl instead of `matches!` to check non-static
`Opcode` 
~~Not very intuitively, `assert!(matches!(opcode, op))` is producing a `match opcode` and `op` is placed in the catch-all position, so not testing the match at all~~ see comments

Minor clippy fixes

---

.cargo/config.toml
Cargo.toml
src/script/op_codes.rs
src/wasm/commitments.rs
src/wasm/key_utils.rs
src/wasm/keyring.rs
src/wasm/range_proofs.rs
wasm-demo.js
wasm.sh

- Add extensive unit test coverage for WASM libs
- Use optional `getrandom` dependency for the `wasm` feature and turn on
`getrandom/js`
(https://docs.rs/getrandom/0.2.3/getrandom/#unsupported-targets)
- Re-add rangeproof verify WASM (works with `wasm-demo`)
- Add `wasm_bindgen_test` dev-dependency
- Add `wasm.sh` script to run tests (`./wasm.sh test`) and builds (`./wasm.sh build`)

WASM unit tests

---

src/ristretto/ristretto_keys.rs

During deserialization, the compress and decompress method is called, when only one of them needs to be.
This should halve the time during `from_bytes()`

fix: remove extra compress call during pubkey::deserialize

---

src/wasm/key_utils.rs

Use of code variable names that match the math conventions in documentation
is preferred.

Revert naming in wasm functions

---

src/script/op_codes.rs
src/script/stack.rs
src/script/tari_script.rs

This PR is to combat a memory leak for the console wallet in Ubuntu 18.04 and 20.04. 
Instrumenting the console wallet with https://docs.rs/dhat/0.2.2/dhat/ and testing with `valgrind --tool=dhat` highlighted `Script` and `ExecutionStack` as the culprits. Pre-allocation of `Script` and `ExecutionStack` vectors (`Vec::with_capacity(512)`) resulted in memory usage of 12GB vs. 4.4GB when using `Vec::new()` for a large wallet.
View with https://nnethercote.github.io/dh_view/dh_view.html
**With this PR**
[dhat-heap.json.30285_vec_new.log](https://github.com/tari-project/tari-crypto/files/7167562/dhat-heap.json.30285_vec_new.log)
**Pre this PR**
[dhat-heap.json.19190.log](https://github.com/tari-project/tari-crypto/files/7167554/dhat-heap.json.19190.log)

fix: reduce memory allocation on execution_stack and scripts

---

.github/workflows/source-cov.yml

- Coverage GA is broken for PRs
- It's not necessary to run code coverage for every PR

Don't do source code coverage on PRs

---

.github/workflows/test.yml
Cargo.toml

We want to be able to use the latest tari_utilities in the main Tari repo rather than having to push new versions to crates but `tari_crypto` re-exports the crates version.
So updating `tari-crypto` to point at the `tari_utilities` git repo too for faster iteration.

chore: point tari_utilities to the git repo

---

src/script/stack.rs
src/script/tari_script.rs

- Check that ExecutionStack does not exceed MAX_STACK_SIZE (255) when decoding from bytes
- Add `size()` to tari script ~~required to limit the maximum number of script elements in transaction and block validation~~

fix: ensure ExecutionStack cannot exceed MAX_STACK_SIZE

---

Cargo.toml
src/ristretto/ristretto_keys.rs

Replaces unmaintained `clear_on_drop` crate with `zeroize` (used by `curve25519-dalek`)
EDIT: another approach could be to call `zeroize()` on the Scalar on `RistrettoSecretKey` drop since it doesn't add any extra data. But, looking into the zeroize code, it all boils down to the same thing.

refactor: replace clear_on_drop with zeroize

---

.github/workflows/test.yml
Cargo.toml
Makefile
README.md
src/ristretto/dalek_range_proof.rs
src/ristretto/pedersen.rs
src/ristretto/ristretto_keys.rs

Implement lazy compression for RistrettoPublicKey using thread-safe [`OnceCell`](https://docs.rs/once_cell/latest/once_cell/index.html) (currently unstable in std) 
Red is on current main branch, blue are the changes in the PR
- Minor optimisation for lexicographical public key ordering: using reference to the underlying compressed array rather than copying the array onto the stack and then creating a reference

perf: lazily compress RistrettoPublicKey

---

.github/workflows/wasm.yml
Makefile

- Adds a new github action to run on pull requests and pushes to the main branch.
- Checks that wasm compiles and tests successfully 
- If the action is triggered on push to `main` then the wasm artifacts are uploaded as well

ci: add wasm build artifacts and test run

---

.github/workflows/clippy-check.yml
benches/signatures.rs
lints.toml
src/ffi/keys.rs
src/lib.rs
src/ristretto/constants.rs
src/ristretto/dalek_range_proof.rs
src/ristretto/ristretto_com_sig.rs
src/ristretto/ristretto_keys.rs
src/signatures/commitment_signature.rs
src/wasm/key_utils.rs

- adds lint config for [`cargo-lints`](https://crates.io/crates/cargo-lints)
- uses `cargo-lints` in CI
- fixes clippy errors
- Breaking: changes method signature of RistrettoComSig::sign to pass in references (clippy::needless-pass-by-value)

chore!: adds clippy lints config and fix lints

---

README.md
changelog.md

Moved the old changelog from `readme.md` to `changlelog.md`.
Prettier also applied some changes.

chore: move old changelog from readme to changelog.md

---

Cargo.toml
src/ristretto/ristretto_keys.rs

- updates tari_crypto to git tag v0.4.0
- remove deprecated ExtendBytes usage

chore: upgrade tari_utilities to latest tag

---

src/errors.rs
src/lib.rs
src/range_proof.rs
src/rewindable_range_proof.rs
src/ristretto/dalek_range_proof.rs

Split rewindable range proofs from the range proof trait into its own trait in preparation for adding Bulletproofs+, as not all rangeproofs are rewindable.

chore: split range proof trait

---

Cargo.toml
benches/range_proof.rs
src/commitment.rs
src/errors.rs
src/ffi/keys.rs
src/rewindable_range_proof.rs
src/ristretto/constants.rs
src/ristretto/dalek_range_proof.rs
src/ristretto/pedersen/commitment_factory.rs
src/ristretto/pedersen/extended_commitment_factory.rs
src/ristretto/pedersen/mod.rs
src/ristretto/ristretto_com_sig.rs
src/wasm/commitments.rs
src/wasm/key_utils.rs
src/wasm/keyring.rs
src/wasm/range_proofs.rs

Added extended ristretto commitment factory for Pedersen commitments making use of the extended Pedersen generators in the Tari Bulletproofs+ library.
Notes:
- `RISTRETTO_NUMS_POINTS` have been updated by sequentially hashing the domain separated Ristretto255 generator point instead of sequentially hashing the generator point only. Domain separated hashing is less likely to result in unintended collisions or reuse elsewhere.
- An `ExtendedHomomorphicCommitmentFactory` trait has been added
- `ristretto/pedersen` has been changed into a module that defines `pedersen/commitment_factory` and `pedersen/extended_commitment_factory`
- `PedersenCommitmentFactory` and `ExtendedPedersenCommitmentFactory` use the same base `G` and `H` generator points so that each factory produces the same …

feat: add extended ristretto commitment factory and pedersen generators

---

Cargo.toml

The upgrade of the `tari_utilities` crate to `0.4.4` version.

chore: upgrade tari_utilities version to 0.4.4

---

Cargo.toml
src/extended_range_proof.rs

Using `curve25519-dalek = { package = "curve25519-dalek-ng", version= "4.1"`
instead of `curve25519-dalek = { package = "curve25519-dalek", version = "4.0.0-pre.2"`
due to issues with `zeroize`

chore: revert 'curve25519-dalek'

---

README.md
src/wasm/range_proofs.rs

Added bulletproof_plus interfaces to wasm

feat: add bulletproof_plus to wasm

---

Cargo.toml
src/wasm/range_proofs.rs

- Updated ` cargo.toml` with proper tags for `tari_bulletproofs` and `tari_bulletproofs_plus`
- Improved some naming in wasm bindings

chore: add bp and bp+ tags to cargo.toml

---

src/errors.rs
src/hashing.rs
src/lib.rs
src/ristretto/ristretto_keys.rs

Naive hashing of data for various applications (key derivation,
signature challenges, hmacs, group generators, etc.) can have subtle
security implications if not done carefully. The hashing API strives to
adopt the implicit use of best practices for these applications using an
API that is:
* super ergonomic and stays largely out of the way.
* leverages the Rust type system to achieve zero-cost abstractions and
guarantees that best practices are being followed.
* Performing these best practices in tari-crypto, and letting clients
focus on their applications.
The API makes heavy use of traits (incl marker traits) and generics to
keep the API as flexible and broadly applicable as possible.

feat: hashing api

---

.github/workflows/clippy-check.yml
src/hashing.rs
src/ristretto/ristretto_keys.rs

Hashing is an extremely common operation and therefore should avoid using the heap. 
This PR removes the allocation of the hash, the full tag string, and the label string from the `DomainSeparatedHasher`.  
~~BREAKING CHANGE: the version byte was previously converted to a decimal string representation before being applied to the digest. In order to maintain the same hashes, an allocation would necessarily`*` be required i.e. `let v_str = Self::version().to_string()`. Instead, the version byte is used directly in the challenge.~~
~~`*` barring some fancy use of `std::fmt::Formatter`~~
Fixes #113
New commit:[b591398](https://github.com/tari-project/tari-crypto/pull/116/commits/b591398c7e634b4e025a081614e51e8d65271201) Generates the ASCII byte representation for the version number without a …

fix(hashing): avoid heap allocations for domain-separated hashing API

---

src/ristretto/ristretto_keys.rs

Fixes for https://github.com/tari-project/tari/issues/3822
Secret keys will never be printed until they are revealed explicitly with the `.reveal()` method call.

fix: don't print a secret key by default

---

src/hash/blake2.rs
src/hash/error.rs
src/hash/mod.rs

It adds checking for `Blake256` parameters: salt and persona should be less or equal 16 bytes length.
Motivation: the fixes for #110.

fix: add checking for Blake256 parameters

---

src/keys.rs
src/ristretto/ristretto_keys.rs

It adds a const `KEY_LEN` to the `PublicKey` trait that specifies the associated key length.

feat: refactor PublicKey length trait to accomodate specific KEY_LEN const

---

src/hashing.rs
src/ristretto/ristretto_keys.rs

Implements `Digest` for DomainSeparatedHasher with a blank default label
Deleted `GenericHashDomain`
Motivation
---
This means you can use a DomainSeparatedHasher in any function that already uses Digest. Unfortunately, the label must be blank, so the `domain` should be different for struct.
I also added a macro `hashing_domain` for creating domains quickly (e.g. for tests)
```rust
hash_domain!(MyDemoHasher, "macro.test");
// Generates
pub struct MyDemoHasher {}
impl DomainSeparation for MyDemoHasher {
fn version() -> u8 {
1
}
fn domain() -> &'static str {
"macro.test"
}
}   
``` 
After adding the `hash_domain` macro it is now easy enough to create a new domain when you need it, removing the need for `GenericHashDomain`. I found that devs were trying to build on top of it instead of …

feat: implement Digest for DomainSeparatedHasher

---

src/hashing.rs
src/ristretto/ristretto_keys.rs

Changed `create_hasher!` macro into a helper function instead, since in most cases you want to reuse the domain created.
Created a macro for creating a type aliased hasher and domain in one called `hasher!` 
e.g.
```
hasher!(Blake256, MyDemoHasher, "com.macro.test");
MyDemoHasher::new("label").chain(data).finalize();
```

feat: add hasher macro

---

Cargo.toml

Upgrade `tari-utilities` dependency to `0.4.5` version.

chore: upgrade tari_utilities version to 0.4.5

---

src/errors.rs
src/hashing.rs
src/ristretto/ristretto_keys.rs

With applying the new hashing API in the tari project some some suggestions are made to improve its use-ability:
- Renamed `DomainSeparatedHasher::<D, M>::new()` to   `DomainSeparatedHasher::<D, M>::new_with_label(label: &'static str)`
- Added `DomainSeparatedHasher<D, M>::new()` to to be functionally equivalent to `D::new()` due to use of `<DomainSeparatedHasher<D, M> as Digest>`
- Added `pub trait HashToBytes`
- Added a digest convenience function to the hashing API
_**Note:** The new error type `SliceError` must be `serde::{Deserialize, Serialize}` compatible and can therefor not be included in `HashingError`_

feat: synchronize the standard digest `new()` with `domain separated hasher::new()`

---

src/hashing.rs

As per https://rust-lang.github.io/api-guidelines/interoperability.html
When using the hash domain in structs, most commonly with `#derive(Debug, Clone)]`, the code fails to compile
and manual implementations are required.

feat(hashing): eager implement common traits

---

Cargo.toml
benches/range_proof.rs
src/ristretto/bulletproofs_plus.rs

Move away for `curve25519-dalek-ng` and rather use `curve25519-dalek` as this is the more updated repo.
Updated the version as this is a breaking change with respect to dependencies.
Matched the version of `rand` to `rand_core` so that the traits can work.

feat: port dalek

---

Cargo.toml

Only includes `rand/wasm-bindgen` when the `wasm` feature is active.
It's not clear why stdweb was added. Since some wasm targets include rust stdlib, or are no_std. If required, it should probably be behind another feature flag. EDIT: https://rustsec.org/advisories/RUSTSEC-2020-0056.html

fix: include wasm features only if required

---

src/dhke.rs
src/keys.rs
src/lib.rs
src/ristretto/ristretto_keys.rs

Adds support for `Zeroize` to both the `RistrettoSecretKey` and `RistrettoPublicKey` types, and creates a new shared secret type. Adds a test for both key types.
This work adds derived `Zeroize` support to `RistrettoSecretKey` to support the use case where we want to clear a secret key in scope.
It also adds custom `Zeroize` support to `RistrettoPublicKey`. In this case, we zeroize both the underlying `RistrettoPoint` and the `CompressedRistrettoPoint` contained in a `OnceCell`. This is useful in the case where a `RistrettoPublicKey` represents secret data, like in the case of a Diffie-Hellman shared secret. Note that we do not zeroize on drop, so this use case must be handled manually, ideally through the use of a `Zeroizing` wrapper.
Finally, it adds a new generic …

feat: add `Zeroize` support to key types, and create new shared secret type

---

benches/commitment.rs
benches/mod.rs
src/ristretto/constants.rs
src/ristretto/pedersen/commitment_factory.rs

This work adds precomputation support for Pedersen commitments that use a provided generator. Basepoint tables are created via `lazy_static` alongside the generators themselves. When computing a commitment using the default generators, the corresponding tables are used. Commitments using any other generators are unchanged.
Closes [issue #135](https://github.com/tari-project/tari-crypto/issues/135).

feat: use precomputation for default commitments

---

src/ffi/keys.rs
src/ffi/mod.rs
src/ristretto/mod.rs
src/ristretto/ristretto_com_and_pub_sig.rs
src/signatures/commitment_and_public_key_signature.rs
src/signatures/commitment_signature.rs
src/signatures/mod.rs
src/wasm/key_utils.rs

Commitment signatures are currently used (via the `CommitmentSignature` type) in Tari protocols as part of transaction authorization, as described in [RFC-0201](https://rfc.tari.com/RFC-0201_TariScript.html). The cryptographic design of commitment signatures is such that they are a representation proof of a Pedersen commitment that is bound to arbitrary message data (via a Fiat-Shamir challenge) to produce a signature.
In both cases where commitment signatures are used, two elements of input data are summed prior to generating or verifying the signature. The cases are:
- an output commitment and a sender offset public key
- an input commitment and a script public key
In both cases, the individual elements are included separately in the challenge.
This approach is not a proof of knowledge …

feat: add new commitment signature to use complete representation proof

---

Cargo.toml
src/wasm/commitments.rs
src/wasm/key_utils.rs
src/wasm/keyring.rs
src/wasm/range_proofs.rs

`JsValue::from_serde` and `.into_serde` can cause cyclic dependency issues, and need to be replaced by serde-wasm-bindgen function calls.
As a side affect,
WASM binary sizes are reduced and performance increases (uncorroborated)

fix: resolve wasm deprecation warnings

---

Cargo.toml
benches/signatures.rs
src/ffi/keys.rs
src/hashing.rs
src/ristretto/mod.rs
src/ristretto/ristretto_sig.rs
src/ristretto/utils.rs
src/signatures/schnorr.rs
src/wasm/key_utils.rs
src/wasm/keyring.rs

There are some footguns in the `SchnorrSignature::sign` method that this
PR seeks to mitigate.
Firstly, it's not clear in the function docs that the nonce and pubkey
are assumed to have been bound by the caller in the challenge.
The docs are updated to make this clearer.
Secondly, we deprecate the sign method and the utility module's sign
method in favour of:
- `sign_raw`, which is identical to the current sign method, but with a
name that conveys the risk associated with using it.
- `sign_message`, which does what many clients might have thought `sign`
does, which correctly binds a nonce and public key to the message
being signed in the challenge construction.
- Matching `verify_*` methods.
Tests and docs have been updated to reflect the changes.
The WASM and FFI library now use the …

feat!: improve signature api 

---

src/signatures/schnorr.rs

The recent [update](https://github.com/tari-project/tari-crypto/pull/145) to the Schnorr signature API introduced a breaking serialization change due to the presence of a new `PhantomData` field that serializes to a null value, which breaks compatibility with existing signatures.
This work introduces a simple change that instructs `serde` to ignore the field during serialization and deserialization. There shouldn't be any other problems with deserialization, since `serde` will apply the correct default type.
BREAKING CHANGE: Technically this is a breaking change to serialization, even though it restores the expected serialization for proper compatibility with other crates.

fix!: signature serialization

---

Cargo.toml
src/hashing.rs

Updates the `tari_utilities` dependency to support the new hidden type API. Adds a test that the new `SafeArray` type plays nicely with the hashing API.
Supersedes [PR 151](https://github.com/tari-project/tari-crypto/pull/151).

feat: update `tari_utilities` and tests

---

src/ristretto/pedersen/commitment_factory.rs
src/ristretto/pedersen/extended_commitment_factory.rs
src/ristretto/pedersen/mod.rs

Added use of pre-computation tables for commitment scalar multiplication to the Ristretto Pedersen extended commitment factory if extension degree = 1, similar to what is done for the normal Ristretto Pedersen commitment factory.

feat: use pre-computation tables for extended commitment factory with extension degree = 1

---

Cargo.toml
src/deterministic_randomizer.rs
src/lib.rs

This is a proof of concept for a deterministic shuffler and bounded number generator for use in consensus-critical applications. It provides a generic API that lets you choose your favorite CSPRNG.
Some protocol applications are likely to require the use of consensus-based pseudorandomness. For example, the network may need to choose or shuffle among validator nodes using chain state data as a common seed. This means that all such nodes must take this seed and use it to arrive at the same results. While `rand` has generic functionality for these kinds of operations using any random number generator, there is no guarantee that its algorithms for doing so will be the same across versions, which could lead to dependency issues.
This work provides one design that has no `rand` dependency. It …

feat: deterministic pseudorandom operations

---

.github/workflows/test.yml

Currently, no features are subject to CI testing. This is bad.
The CI system now runs only on `stable`. All feature-based CI tests are stuck behind an `if` clause that prohibits testing on `stable`, presumably because of an earlier version that used `--all-features` instead of selectively enabling them. This means they are never run.
This PR ensures that the feature tests for `wasm` and `ffi` and `borsh` are run.

test: run feature CI tests

---

src/ristretto/constants.rs

The documentation for the nothing-up-my-sleeve (NUMS) construction of a set of Ristretto group generators references an unrelated IETF draft. This PR removes this reference to update the documentation.

docs: fix Ristretto NUMS documentation

---

src/ristretto/ristretto_sig.rs

One of the signature doc examples was incorrectly formatted. As a result it wasn't picked up as a doc test

fix: typo in docstring

---

src/hashing.rs

Adds `PartialEq, Eq` trait derivations to `DomainSeparatedHasher` structure. These traits are necessary on the Tari DAN, to use Tari's Balanced Merkle Trees structs

feat: add partialeq and eq trait derivation to domain separated hasher

---

src/ristretto/bulletproofs_plus.rs

Added a simple aggregated range proof test to show the minimum constructs needed if we are only interested in an aggregated range proof, possibly with more than one commitment extension degree.

test: add simple aggregated range proof test

---

src/keys.rs
src/ristretto/ristretto_keys.rs

Adds a trait bound requiring that a `SecretKey` zeroize on drop. Derives this trait bound for `RistrettoSecretKey`.
Currently, we use a macro from `zeroize` to zeroize a `RistrettoSecretKey` on drop. This works fine, but doesn't let us require this behavior as a `SecretKey` trait bound. Now that we have a custom curve library fork that supports an updated version of `zeroize`, we can take advantage of a new `ZeroizeOnDrop` derive macro that adds a corresponding marker trait. This PR adds the marker trait as a trait bound to `SecretKey` and uses the derive macro for `RistrettoSecretKey`. This adds an additional layer of safety to secret keys.
Closes [issue #147](https://github.com/tari-project/tari-crypto/issues/147).

feat: require secret keys to be zeroized on drop

---

lints.toml
src/ristretto/bulletproofs_plus.rs
src/ristretto/ristretto_keys.rs

Fixes lint warnings. These weren't errors that failed CI, but clogged up the linter output.

chore: fix lint warnings

---

src/keys.rs
src/ristretto/ristretto_keys.rs

Adds multiplicative inversion to `RistrettoSecretKey`. Adds a few unit tests.
Note that the underlying `invert` functionality from `curve25519-dalek` does not assert that the `Scalar` in question is nonzero, but requires the caller to check this; inverting zero is undefined. This PR specifically checks this, and as a result, the inversion returns an `Option`. This is probably annoying for the caller, but might stop bad things from happening.

feat: `RistrettoSecretKey` inversion

---

.github/workflows/wasm.yml

Previously, an upstream [issue](https://github.com/rustwasm/wasm-pack/issues/1248) with `wasm-pack` resulted in CI failure. Because of this, the dependency was [reverted and frozen](https://github.com/tari-project/tari-crypto/pull/174) at a working version.
A recent `wasm-pack` minor version bump should have this working again. This PR updates and freezes at this version.

build: update `wasm-pack`

---

src/keys.rs
src/ristretto/ristretto_keys.rs

Currently, the `PublicKey` trait exposes the encoded key byte length via the associated `KEY_LEN` constant, and also provides it via the `key_length` function. However, the `SecretKey` trait only exposes its encoded key byte length via the `key_length` function, which cannot be constant. There are use cases where it's handy to get the key size at compile time, particularly when you want to use arrays and avoid heap allocations.
This PR unifies the `PublicKey` and `SecretKey` traits by adding an associated `KEY_LEN` constant to `SecretKey`. It then updates the `RistrettoSecretKey` implementation accordingly. This retains all existing functionality, so the change is not breaking.

feat!: expose secret key length as a constant

---

src/ristretto/bulletproofs_plus.rs

There's a warning about an allegedly suspicious borrow in one of the range proof tests. It's likely [already fixed](https://github.com/rust-lang/rust/issues/112489), but easy enough to use the ampersand operator to clean up the warning.

chore: fix a spurious lint

---

src/ristretto/ristretto_keys.rs

- Fixed `pub fn new_generator(label: &'static str)` too few bytes error (DigestTooShort)
- Added a test case for `pub fn new_generator`

feat: fix new_generator

---

.github/workflows/clippy-check.yml
Cargo.toml
README.md
benches/signatures.rs
src/commitment.rs
src/deterministic_randomizer.rs
src/dhke.rs
src/errors.rs
src/extended_range_proof.rs
src/hashing.rs
src/keys.rs
src/lib.rs
src/ristretto/bulletproofs_plus.rs
src/ristretto/constants.rs
src/ristretto/mod.rs
src/ristretto/pedersen/commitment_factory.rs
src/ristretto/pedersen/extended_commitment_factory.rs
src/ristretto/pedersen/mod.rs
src/ristretto/ristretto_keys.rs
src/ristretto/ristretto_sig.rs
src/ristretto/serialize.rs
src/ristretto/utils.rs
src/signatures/commitment_and_public_key_signature.rs
src/signatures/commitment_signature.rs
src/signatures/schnorr.rs

This PR adds in no_std support for TariCrypto. 
The following changes where made to enable this:
- thiserror was swapped out for Snafu as thiserror does not support no_std while snafu does.
- use std::  was changed to use core::
- make all dependencies default-features = false
- make BulletProofPlus an optional feature
- make serde an optional feature
- Make precomputed_tables optional as they require large internal memory
- remove lazy_static as a dependency (replaced by one-cell)
- changed sign message to use supplied RNG, and not thread_local internally

feat!: enable no_std support for tari_crypto

---

Cargo.toml
changelog.md

* enable no_std support for tari_crypto (#191)
* move the WASM and FFI builds to seperate Repos (#193)
* enable no_std support for tari_crypto ([191](https://github.com/tari-project/tari-crypto/issues/191)) ([a0e9765](https://github.com/tari-project/tari-crypto/commit/a0e9765d2b96a3f8c3bdb5c3c80ff3afd26ce97b))
* fix new_generator ([192](https://github.com/tari-project/tari-crypto/issues/192)) ([0d463b0](https://github.com/tari-project/tari-crypto/commit/0d463b064e6e41c1c0d1ff2064afa0b3f7f6bac9))
* move the WASM and FFI builds to seperate Repos ([193](https://github.com/tari-project/tari-crypto/issues/193)) ([053119f](https://github.com/tari-project/tari-crypto/commit/053119f2110aaf3089c7b9df96f50b8cc8d3217a))
* remove unused dalek rangeproof …

chore: release 0.18.0

---

src/dhke.rs

Simplifies the implementation of zeroizing support for Diffie-Hellman key exchanges and improves test coverage.
Currently, the `DiffieHellmanSharedSecret` struct has manual implementations of `zeroize` and `drop` to handle zeroizing. Now that we have a more modern version of `zeroize` as a dependency, we can do better. This PR uses that crate's `Zeroize` and `ZeroizeOnDrop` derived traits to handle this more cleanly. It also adds a sanity check that the byte representations of both sides of a key exchange match, which improves test coverage.
Partially addresses #196.

feat: simplify zeroizing and add test to DHKE

---

.github/workflows/audit.yml
.github/workflows/check_licence.yml
.github/workflows/clippy-check.yml
.github/workflows/source-cov.yml
.github/workflows/test.yml

This PR updates CI actions.
Because the `actions-rs` project is [unmaintained](https://github.com/actions-rs/toolchain/issues/216), this is replaced with the [maintained](https://github.com/dtolnay/rust-toolchain) `dtolnay/rust-toolchain` action. The outdated `checkout` action version is [updated](https://github.com/actions/checkout/releases/tag/v4.0.0). Documentation builds are [flagged](https://doc.rust-lang.org/cargo/commands/cargo-doc.html#documentation-options) to avoid dependencies, which aren't needed.

ci: update CI actions

---

lints.toml

There are currently several `clippy` [groups](https://github.com/rust-lang/rust-clippy#clippy) that are useful, but are not included in `lints.toml`. This PR adds the default `clippy::all` group to the deny list, and cleans up some individual lints that are made redundant by this change. No code changes are needed as a result of this.

test: expand and clean up lints

---

src/ristretto/bulletproofs_plus.rs

Tests are currently slow, mainly due to the parameters used in range proof tests. This PR simplifies these parameters to speed up tests while still exercising the required functionality.
Closes #200.

test: optimize range proof tests

---

src/extended_range_proof.rs
src/ristretto/pedersen/extended_commitment_factory.rs
src/ristretto/ristretto_keys.rs

This adds `Zeroize` and `ZeroizeOnDrop` to `ExtendedMask` and `ExtendedWitness` for improved memory handling functionality. It restricts the visibility of an internal commitment constructor and adds zeroizing to temporary secret values. It updates secret key deserialization to add zeroizing to a temporary byte array. Finally, it removes a secret key constructor.
Supersedes #204.
BREAKING CHANGE: Changes the commitment and secret key APIs.

fix!: improve zeroizing support

---

Cargo.toml

There are cases where std is needed (barring workarounds). E.g. errors implementing std::error::Error. 
This PR adds the ability to opt-in to the stdlib.

fix: add opt-in std support

---

Cargo.toml
changelog.md
src/commitment.rs
src/ristretto/ristretto_keys.rs

chore: upgrade borsh

---

src/commitment.rs

Nightly `clippy` incorrectly reports that the commitment `PartialEq` [implementation](https://github.com/tari-project/tari-crypto/blob/017bb2cde069fc8a1b1a6014f339e59dc7fd6ca7/src/commitment.rs#L157-L161) recurses. Changing the syntax to use `==` seems to fix this and does the same thing.
Closes #220.

ci: fix lint error

---

.github/workflows/clippy-check.yml

Sadly, nightly CI is borked due to an [upstream issue](https://github.com/dalek-cryptography/curve25519-dalek/issues/618) identified with a recent nightly release.
This PR pins the nightly toolchain at a working version.

ci: pin nightly toolchain

---

Cargo.toml
src/dhke.rs
src/keys.rs
src/ristretto/ristretto_keys.rs

Currently, the only implementation of the `SecretKey` and `PublicKey` traits is for Ristretto, where both [scalars](https://github.com/dalek-cryptography/curve25519-dalek/blob/ba737a379071191158bacfa6d138f6249b12fc09/curve25519-dalek/src/scalar.rs#L296-L300) and [group elements](https://github.com/dalek-cryptography/curve25519-dalek/blob/ba737a379071191158bacfa6d138f6249b12fc09/curve25519-dalek/src/ristretto.rs#L822-L826) use constant-time equality in their underlying `PartialEq` implementations, and which support the `ConstantTimeEq` trait.
This PR does what it can to encourage the use of constant-time equality for keys by doing a few things.
First, it requires that any types implementing `SecretKey` or `PublicKey` also implement `ConstantTimeEq`. Unfortunately, this doesn't guarantee …

feat: add constant-time trait bounds

---

src/ristretto/ristretto_com_and_pub_sig.rs
src/ristretto/ristretto_com_sig.rs
src/ristretto/ristretto_sig.rs
src/signatures/commitment_and_public_key_signature.rs
src/signatures/commitment_signature.rs
src/signatures/schnorr.rs

Signature verification currently allows identity elements:
- `SchnorrSignature` allows an identity public key
- `CommitmentSignature` allows an identity commitment
- `CommitmentAndPublicKeySignature` allows both
This doesn't strictly break soundness, but does remove message binding. While it shouldn't be problematic for unforgeability, it's a case that shouldn't arise from an honest signer and is easy to check for.
This PR fails signature verification if such an identity element is provided, and adds tests for each case. It does _not_ return an error if the corresponding identity elements are provided by the signer, since this precludes useful partial signature operations.

fix: reject identity keys and commitments in signatures

---

Cargo.toml
changelog.md
src/dhke.rs
src/hashing.rs

feat: add pub constructor to DHKE

---

Cargo.toml
changelog.md
src/ristretto/ristretto_com_and_pub_sig.rs
src/signatures/commitment_and_public_key_signature.rs

Adds sum for schnorr signature and capk signature as a features
new version

feat: add sum for schnorr signature and capk signature

---

src/dhke.rs

This PR ensures that `DiffieHellmanSharedSecret` equality testing is done in constant time.
Previously, this equality testing was offloaded to the underlying `PublicKey` type. While this type supports the `ConstantTimeEq` trait, it is not guaranteed that equality testing will use this in all implementations.

feat: use constant-time equality checking for DHKE

---

Cargo.toml
benches/commitment.rs
benches/signatures.rs
changelog.md
lints.toml
src/ristretto/ristretto_keys.rs
src/ristretto/serialize.rs
src/signatures/commitment_signature.rs

update tari utilities to 0.8
update borsh to 1.5
Release new version

feat: update dependancies

---

src/ristretto/ristretto_keys.rs

Ristretto public key zeroizing is done manually due to the use of `OnceCell`. I recently came across a [clever design pattern](https://github.com/BLAKE3-team/BLAKE3/blob/master/src/lib.rs#L447-L466) that uses destructuring. The idea is that future changes to the underlying struct will trigger a compiler error to ensure that the zeroization implementation is also updated.
This PR implements such a change.

chore: protect public key zeroization against updates

---

.github/workflows/clippy-check.yml
Cargo.toml
src/deterministic_randomizer.rs
src/lib.rs
src/ristretto/constants.rs
src/ristretto/pedersen/mod.rs
src/ristretto/ristretto_keys.rs

removes onecell, and replaces it with the rust version
This is breaking to due to the removal of no_std for now. This is required by the removal of oncecell and replaced with rust std version.

feat!: remove onecell
