.github/workflows/audit.yml, .github/workflows/clippy-check.yml, README.md
Add Clippy and security audit actions
=> Clippy action

src/commitment.rs, src/ristretto/musig.rs, src/ristretto/ristretto_keys.rs, src/ristretto/ristretto_sig.rs, src/wasm/key_utils.rs, src/wasm/keyring.rs, src/wasm/range_proofs.rs
* Explicitly implement PartialEq on RistrettoSecretKey and
HomomorphicCommitment
* Add is_empty() to KeyRing
* Fix doctest
=> Fix clippy hints

Cargo.toml, src/musig.rs, src/range_proof.rs, src/signatures.rs
=> Switch error library to this error

src/ristretto/pedersen.rs, src/ristretto/ristretto_sig.rs
A few extra tests to improve code coverage
=> Additional tests

src/script/tari_script.rs
This PR adds an example for the time locked contract example from RFC-0202. It also update the `pay_to_public_key_hash` example to be inline with what is described in the RFC.
=> Add time locked contract example for TariScript

src/wasm/key_utils.rs
This PR adds a number of methods to the WASM interface to create private keys and do some basic private key arithmetic.  This allows a client to aggregate private keys. This is being used in the cucumber tests in the main Tari repo to build the components required for TariScript transactions.
This will require an update to the NPM package of the WASM interface.
=> Add private key utility functions to the WASM interface

.gitignore, src/hash/blake2.rs, src/ristretto/dalek_range_proof.rs, src/ristretto/pedersen.rs, src/ristretto/ristretto_keys.rs, src/script/op_codes.rs, test_coverage.sh
* Delete old coverage files before profiling
* Add test cases
=> Increase coverage > 90%

.github/workflows/source-cov.yml, test_coverage.sh
Update code coverage script and CI to use nightly.
=> fix: use nightly for code coverage

Cargo.toml, src/lib.rs, src/ristretto/mod.rs
=> chore: feature-gate musig (closes #71)

src/hash/blake2.rs
Allows personalisation of Blake2 hash
=> feat: allow custom hash parameters to be specified

.github/workflows/clippy-check.yml, src/ffi/error.rs, src/ffi/keys.rs, src/hash/blake2.rs, src/musig.rs, src/range_proof.rs, src/ristretto/musig.rs, src/ristretto/pedersen.rs, src/ristretto/ristretto_com_sig.rs, src/ristretto/ristretto_keys.rs, src/ristretto/test_common.rs, src/signatures/schnorr.rs, src/wasm/commitments.rs, src/wasm/key_utils.rs, src/wasm/keyring.rs, src/wasm/range_proofs.rs
- all `--all-features` to clippy lints in CI
- fix clippy lints
- adds a few docstrings that were missing.
=> fix: fix clippy lints and add additional docstrings 

Cargo.toml
Swapped out curve25519-dalek-ng for curve25519-dalek in preparation for bulletproofs-plus
=> chore: swap out curve25519-dalek-ng for curve25519-dalek

Cargo.toml, src/commitment.rs, src/errors.rs, src/extended_range_proof.rs, src/lib.rs, src/ristretto/bulletproofs_plus.rs, src/ristretto/dalek_range_proof.rs, src/ristretto/mod.rs, src/ristretto/pedersen/extended_commitment_factory.rs, src/ristretto/pedersen/mod.rs, src/ristretto/ristretto_keys.rs
=> feat: add extended range proofs

Cargo.toml, src/extended_range_proof.rs, src/lib.rs, src/rewindable_range_proof.rs, src/ristretto/bulletproofs_plus.rs, src/ristretto/ristretto_keys.rs
Added simple bulletproofs plus interface that does not support extended masks or aggregated proofs.
=> feat: add simple bulletproofs plus interface

src/hashing.rs
Removed trailing dot in domain tag if an empty label is provided to `DomainSeparatedHasher::new_with_label`
This conveys the message that a label is not expected, but is optional.
=> feat: remove trailing dot with empty label

.github/workflows/clippy-check.yml
=> ci: clippy all features

src/ristretto/ristretto_com_and_pub_sig.rs
Add better tests for `ristretto_com_and_pub_sig`
Also, prove that partial signing is possible.
=> chore: add partial com and pub sigs tests

Cargo.toml
Point to `tari-project/curve25519-dalek` where zeroize is relaxed
=> feat: relax zeroize

src/signatures/schnorr.rs
All impls for `SchnorrSignature` only applied to the SchorrSigChallenge hash domain. 
This PR fixes that by implementing them for any hash domain
=> fix: make schnorr sig impls apply for any hash domain

Cargo.toml, src/ristretto/bulletproofs_plus.rs
Uses a new [range proof API](https://github.com/tari-project/bulletproofs-plus/pull/22).
=> fix: use updated range proof API

src/hash/blake2.rs
When instantiating a `Blake2b` hasher, parameters need to be checked for validity. Currently, the salt, persona, and output lengths are checked to ensure they are valid. However, the key length is not checked, which can lead to a panic.
This PR checks for a valid key length (between 0 and 64 bytes). It also adds a test for each parameter to ensure proper failure.
=> fix: check for valid `Blake2b` keys and test parameters

src/ristretto/ristretto_keys.rs
The `Formatter` used in the rust `Display` trait has several lesser-known features that can be leveraged for making displaying public keys much nicer:
Given some public key instance, `pk`, equal to
`e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76`,
1. truncated Width formating
`format!("{pk:16}")` gives you `e2f2ae...08d2d76`
2. Padding and fills Widths > 64 characters let you pad and fill:
`format!("{pk:*<66}")` gives
`e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76**`
3. Implementing lowerHex and UpperHex traits
Displaying a public key writes the lower hex by default, but you can now specify the hex format explicitly, including using the [expected alternate forms](https://doc.rust-lang.org/std/fmt/trait.LowerHex.html):
```rust
assert_eq!( …
```
=> feat: qual of life improvements for pubkey display

.github/workflows/source-cov.yml
The envar context reference is incorrect.
=> fix: source coverage workflow

src/hash/blake2.rs, src/ristretto/pedersen/commitment_factory.rs, src/ristretto/pedersen/extended_commitment_factory.rs
=> chore: fix lint warnings

src/ristretto/constants.rs
Small PR that makes sure this test runs on 32 bit and 64 bit machines
=> test: replace usize with u64

Cargo.toml, changelog.md
Ups the version and creates a new release version
=> chore: new release 0.19.0

Cargo.toml, changelog.md
=> chore: new version 0.20.1

Cargo.toml, changelog.md
=> chore: new release 0.22.0
